apiVersion: v1
kind: Service
metadata:
  name: node-app-srv
  namespace: vaccinefront
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vaccine-front-app
  type: NodePort