apiVersion: v1
kind: Service
metadata:
  name: react-app-srv
  namespace: vaccinefront
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: vaccine-front-app
  type: NodePort